import { json } from '@sveltejs/kit'; import { AIGateway, stripModelReasoning } from '$server/ai/AIGateway'; import { ScamScoreService } from '$server/services/ScamScoreService';

type RiskAnalysis={riskLevel:string;confidence:string;scamType:string;summary:string;evidence:string[];avoidance:string[];protection:string[];missingInformation:string[];disclaimer:string};
const cleanJson=(value:string)=>{const cleaned=stripModelReasoning(value).replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();const start=cleaned.indexOf('{');const end=cleaned.lastIndexOf('}');return start>=0&&end>start?cleaned.slice(start,end+1):cleaned;};
const parseAnalysis=(value:string):RiskAnalysis|null=>{try{const result=JSON.parse(cleanJson(value));if(!result||typeof result!=='object')return null;return result as RiskAnalysis;}catch{return null;}};
const list=(value:unknown,fallback:string[])=>Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'&&item.trim().length>0).slice(0,8):fallback;
const normalize=(value:RiskAnalysis):RiskAnalysis=>{const risks=['low','medium','high','critical','unknown'];const confidences=['low','medium','high'];const risk=String(value.riskLevel||'unknown').toLowerCase();const confidence=String(value.confidence||'low').toLowerCase();return{riskLevel:risks.includes(risk)?risk:'unknown',confidence:confidences.includes(confidence)?confidence:'low',scamType:String(value.scamType||'unknown').slice(0,100),summary:String(value.summary||'The available information was insufficient for a clear assessment.').slice(0,1200),evidence:list(value.evidence,[]),avoidance:list(value.avoidance,['Verify the target through official channels before interacting.']),protection:list(value.protection,['Disconnect the site and review active wallet approvals.']),missingInformation:list(value.missingInformation,[]),disclaimer:String(value.disclaimer||'This is a risk assessment, not a factual accusation.').slice(0,500)};};

export const POST=async({request})=>{try{const body=await request.json();const target=String(body.target||'').trim().slice(0,500);const description=String(body.description||'').trim().slice(0,3000);if(!target&&!description)return json({error:'Add a target or suspicious activity description.'},{status:400});const heuristics=new ScamScoreService().score(target);const prompt=`You are Poké's evidence-first Web3 scam-risk analyst. Analyze only the supplied user input and heuristic evidence. Never state that a person or project is fraudulent as a fact unless conclusive sourced evidence exists. Missing data must remain unknown. Return only valid JSON with this exact shape: {"riskLevel":"low|medium|high|critical|unknown","confidence":"low|medium|high","scamType":"short classification such as phishing, fake investment, honeypot, impersonation, wallet drainer, rug-pull risk, or unknown","summary":"concise explanation","evidence":["observation with source or user-provided label"],"avoidance":["how a user can recognize and avoid this type of scam before interacting"],"protection":["what an affected user should do now to protect wallet, accounts, or funds"],"missingInformation":["data needed to improve confidence"],"disclaimer":"risk assessment limitation"}. Give 3 to 6 concise items for avoidance and 3 to 6 different, immediate items for protection. Do not include chain-of-thought, analysis, think tags, Markdown, or any text outside the JSON. Target: ${target||'not supplied'}\nUser description: ${description||'not supplied'}\nHeuristic evidence: ${JSON.stringify(heuristics.evidence)}`;const gateway=new AIGateway();let completion=await gateway.complete([{role:'system',content:'Return strict JSON only. Never include reasoning, analysis, think tags, or Markdown.'},{role:'user',content:prompt}]);let parsed=parseAnalysis(completion.content);if(!parsed){completion=await gateway.complete([{role:'system',content:'Convert the supplied draft into the requested strict JSON object. Return JSON only, without reasoning, think tags, or Markdown.'},{role:'user',content:`Required keys: riskLevel, confidence, scamType, summary, evidence, avoidance, protection, missingInformation, disclaimer.\nDraft:\n${completion.content.slice(0,9000)}`}]);parsed=parseAnalysis(completion.content);}if(!parsed)throw new Error('The AI response could not be converted into a clear risk assessment. Please retry.');const analysis=normalize(parsed);return json({analysis,heuristics:heuristics.evidence,scannedAt:new Date().toISOString(),gonka:{requestId:completion.requestId,model:completion.model}});}catch(error){return json({error:error instanceof Error?error.message:'Scan failed'},{status:503});}};
