import { json } from '@sveltejs/kit';
import { AIGateway } from '$server/ai/AIGateway';
import { WebEvidenceService, type RetrievedSource } from '$server/services/WebEvidenceService';

const cleanJson=(value:string)=>value.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();
const parse=(value:string)=>{try{return JSON.parse(cleanJson(value));}catch{throw new Error('Gonka returned an invalid structured verification response.');}};
const clamp=(value:unknown)=>Math.max(0,Math.min(100,Math.round(Number(value)||0)));
const isUrl=(value:string)=>{try{return ['http:','https:'].includes(new URL(value).protocol);}catch{return false;}};
const unique=(values:string[])=>[...new Set(values.filter(Boolean))].slice(0,4);
const array=(value:unknown)=>Array.isArray(value)?value:[];

function normalizeReview(raw:any, allowedUrls:Set<string>){
  const evidence=(items:unknown)=>array(items).slice(0,8).map((item:any)=>({text:String(item?.text||item||'').slice(0,700),sourceUrl:allowedUrls.has(String(item?.sourceUrl||''))?String(item.sourceUrl):''})).filter((item:any)=>item.text);
  return{
    truthScore:clamp(raw?.truthScore),verdict:['supported','mixed','unsupported','unverifiable'].includes(raw?.verdict)?raw.verdict:'unverifiable',
    summary:String(raw?.summary||'The available evidence was insufficient for a conclusion.').slice(0,1400),evidenceFor:evidence(raw?.evidenceFor),evidenceAgainst:evidence(raw?.evidenceAgainst),
    uncertainties:array(raw?.uncertainties).slice(0,8).map(String),reasoningTrace:array(raw?.reasoningTrace).slice(0,8).map((step:any,index:number)=>({step:index+1,label:String(step?.label||`Verification step ${index+1}`),finding:String(step?.finding||''),evidenceRefs:array(step?.evidenceRefs).map(String).slice(0,5)})),
    citations:array(raw?.citations).map((citation:any)=>({title:String(citation?.title||'Evidence source'),url:String(citation?.url||'')})).filter((citation:any)=>allowedUrls.has(citation.url)).slice(0,8)
  };
}

export const POST=async({request})=>{try{
  const body=await request.json();const input=String(body.input||'').trim().slice(0,12_000);if(!input)return json({error:'Paste a claim, URL, or tweet text to verify.'},{status:400});
  const supplied=Array.isArray(body.sourceUrls)?body.sourceUrls.map(String):[];const urls=unique([...(isUrl(input)?[input]:[]),...supplied.filter(isUrl)]);const retriever=new WebEvidenceService();
  const sources=await Promise.all(urls.map(url=>retriever.retrieve(url)));const sourceText=sources.map((source,index)=>`SOURCE ${index+1}\nURL: ${source.url}\nSTATUS: ${source.status}\nCONTENT: ${source.content||source.note||'Unavailable'}`).join('\n\n');
  const gateway=new AIGateway();const extraction=await gateway.complete([{role:'system',content:'You extract checkable factual claims objectively. Return strict JSON only; do not reveal hidden chain-of-thought.'},{role:'user',content:`Extract the main verifiable claims. Separate opinion or requests from facts. Return {"claims":[{"text":"claim","importance":"primary|supporting"}],"inputType":"url|tweet|text","notes":["limitation"]}.\n\nUSER INPUT:\n${input}\n\nRETRIEVED SOURCES:\n${sourceText||'No external source was supplied.'}`}]);
  const extracted=parse(extraction.content);const claims=array(extracted?.claims).slice(0,8).map((claim:any)=>({text:String(claim?.text||claim),importance:claim?.importance==='supporting'?'supporting':'primary'})).filter((claim:any)=>claim.text);
  if(!claims.length)throw new Error('No checkable factual claim was found.');
  const allowedUrls=new Set(sources.filter(source=>source.status==='retrieved').map(source=>source.url));
  const reviewPrompt=`Independently verify these claims using only the supplied source material and your general knowledge. Treat current or changing facts as unverified unless supported by a retrieved source. Be neutral. A Truth Score of 100 means strongly supported, 0 means strongly contradicted, and 50 means mixed or insufficient evidence. Return strict JSON: {"truthScore":0,"verdict":"supported|mixed|unsupported|unverifiable","summary":"plain-language verdict","evidenceFor":[{"text":"observation","sourceUrl":"exact supplied URL or empty"}],"evidenceAgainst":[{"text":"observation","sourceUrl":"exact supplied URL or empty"}],"uncertainties":["missing information"],"reasoningTrace":[{"label":"short auditable step","finding":"what the evidence establishes, without hidden chain-of-thought","evidenceRefs":["SOURCE 1"]}],"citations":[{"title":"source title","url":"exact supplied URL"}]}. Never invent a URL or source.\n\nCLAIMS:\n${JSON.stringify(claims)}\n\nSOURCES:\n${sourceText||'No retrieved sources.'}`;
  const primary=await gateway.complete([{role:'system',content:'You are a neutral public-interest fact checker. Return strict JSON with evidence-based conclusions only.'},{role:'user',content:reviewPrompt}],gateway.primaryModel);const primaryReview=normalizeReview(parse(primary.content),allowedUrls);
  const runs=[{stage:'claim-extraction',requestId:extraction.requestId,model:extraction.model},{stage:'primary-verification',requestId:primary.requestId,model:primary.model}];let final=primaryReview;let consensus:{enabled:boolean;agreement:string;scores:number[];note:string}={enabled:false,agreement:'single-model',scores:[primaryReview.truthScore],note:'Configure GONKA_CONSENSUS_MODEL with a different Gonka-hosted model to enable cross-verification.'};
  if(gateway.consensusModel&&gateway.consensusModel!==gateway.primaryModel){const second=await gateway.complete([{role:'system',content:'You are an independent neutral fact checker. Do not defer to another reviewer. Return strict JSON only.'},{role:'user',content:reviewPrompt}],gateway.consensusModel);const secondReview=normalizeReview(parse(second.content),allowedUrls);const difference=Math.abs(primaryReview.truthScore-secondReview.truthScore);const score=Math.round((primaryReview.truthScore+secondReview.truthScore)/2);final={...primaryReview,truthScore:score,verdict:difference>25?'mixed':score>=75?'supported':score<=25?'unsupported':score>=45&&score<=55?'unverifiable':'mixed',summary:difference>25?`The two Gonka models disagreed materially. Primary review: ${primaryReview.summary} Independent review: ${secondReview.summary}`:primaryReview.summary,uncertainties:[...new Set([...primaryReview.uncertainties,...secondReview.uncertainties])].slice(0,8)};runs.push({stage:'independent-verification',requestId:second.requestId,model:second.model});consensus={enabled:true,agreement:difference<=10?'strong':difference<=25?'moderate':'disputed',scores:[primaryReview.truthScore,secondReview.truthScore],note:difference>25?'The score is marked mixed because the models differed by more than 25 points.':'Final score is the average of two independent Gonka reviews.'};}
  return json({inputType:extracted?.inputType||'text',claims,sources:sources.map(({content,...source})=>source),result:final,consensus,runs,verifiedAt:new Date().toISOString()});
}catch(error){return json({error:error instanceof Error?error.message:'Verification failed.'},{status:503});}};
