<script lang="ts">
  import AppHeader from '$lib/components/AppHeader.svelte';
  type Evidence={text:string;sourceUrl?:string};type Trace={step:number;label:string;finding:string;evidenceRefs:string[]};
  type Verification={inputType:string;claims:Array<{text:string;importance:string}>;sources:Array<{url:string;title:string;fetchedAt:string;status:string;note?:string}>;result:{truthScore:number;verdict:string;summary:string;evidenceFor:Evidence[];evidenceAgainst:Evidence[];uncertainties:string[];reasoningTrace:Trace[];citations:Array<{title:string;url:string}>};consensus:{enabled:boolean;agreement:string;scores:number[];note:string};runs:Array<{stage:string;requestId:string;model:string}>;verifiedAt:string};
  let input='';let sourceText='';let loading=false;let error='';let report:Verification|null=null;
  const samples=[{label:'Text claim',value:'A message says Ethereum support will never ask users to reveal their wallet recovery phrase.'},{label:'Suspicious offer',value:'This investment platform guarantees a 30% weekly return with zero risk and asks users to send cryptocurrency directly to an unknown wallet.'}];
  async function verify(){if(!input.trim()||loading)return;loading=true;error='';report=null;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),95_000);try{const sourceUrls=sourceText.split(/\n|,/).map(value=>value.trim()).filter(Boolean);const response=await fetch('/api/ai/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({input,sourceUrls}),signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||'Verification failed.');report=data;}catch(e){error=e instanceof Error&&e.name==='AbortError'?'Verification took too long. No result was saved; please try again.':e instanceof Error?e.message:'Verification failed.';}finally{clearTimeout(timer);loading=false;}}
  function scoreClass(score:number){return score>=75?'supported':score<=25?'unsupported':'mixed'}
</script>
<svelte:head><title>Verify a claim — Poké</title><meta name="description" content="Verify claims with evidence, Gonka inference request IDs, and an auditable Truth Score."/></svelte:head>
<div class="shell"><AppHeader active="verify"/><main class="verify-page">
  <section class="verify-intro"><div><span class="eyebrow">GONKA TRUTH ENGINE</span><h1>Verify a claim with <em>traceable evidence.</em></h1><p>Paste text, a public webpage URL, or tweet text. Poké separates the claims, retrieves supplied sources, and shows every Gonka inference request.</p></div><div class="network-proof"><i></i><div><small>INFERENCE NETWORK</small><strong>GonkaRouter</strong></div><span>Transparent</span></div></section>
  <section class="verify-workspace"><form class="claim-card" onsubmit={(e)=>{e.preventDefault();verify()}}><div class="card-heading"><span class="step-number">01</span><div><h2>Claim to verify</h2><p>Paste the exact statement or a public URL containing it.</p></div></div><label for="claim">Claim, webpage URL, or tweet text</label><textarea id="claim" bind:value={input} placeholder="Example: Paste a factual claim or https://…" maxlength="12000"></textarea><label for="sources">Supporting or conflicting source URLs <span>optional, one per line</span></label><textarea id="sources" class="source-input" bind:value={sourceText} placeholder="https://official-source.example/article&#10;https://another-source.example/report" maxlength="4000"></textarea><div class="sample-row"><small>Try a sample:</small>{#each samples as sample}<button type="button" onclick={()=>input=sample.value}>{sample.label}</button>{/each}</div>{#if error}<p class="verify-error" role="alert">{error}</p>{/if}<button class="verify-button" disabled={loading||!input.trim()}>{loading?'Gonka is verifying…':'Verify claim'}<span>→</span></button><p class="privacy-note">Public URLs are retrieved by the server. Do not paste private or confidential links.</p></form>
    <aside class="method-card"><span class="step-number">METHOD</span><h2>What Poké checks</h2><ol><li><b>Extract</b><span>Separate factual claims from opinion.</span></li><li><b>Retrieve</b><span>Read the public sources you supplied.</span></li><li><b>Verify</b><span>Run neutral Gonka-hosted analysis.</span></li><li><b>Expose</b><span>Show evidence, limitations, and request IDs.</span></li></ol><div class="method-note"><strong>{loading?'Verification in progress':'Evidence before verdict'}</strong><span>{loading?'Claim extraction and independent review can take up to 90 seconds.':'Missing evidence lowers certainty instead of being treated as proof.'}</span></div></aside>
  </section>
  {#if report}<section class="verification-report" aria-live="polite"><div class="report-top"><div class={`truth-ring ${scoreClass(report.result.truthScore)}`} style={`--score:${report.result.truthScore}`}><strong>{report.result.truthScore}%</strong><small>TRUTH SCORE</small></div><div class="verdict-copy"><span class={`verdict ${report.result.verdict}`}>{report.result.verdict}</span><h2>{report.result.summary}</h2><p>Verified {new Date(report.verifiedAt).toLocaleString()} · Input classified as {report.inputType}</p></div><div class="consensus-status"><small>MODEL CONSENSUS</small><strong>{report.consensus.enabled?report.consensus.agreement:'Single model'}</strong><span>{report.consensus.scores.join(' / ')}</span></div></div>
    <div class="report-grid"><div class="report-main"><section><div class="section-label"><span>02</span><h3>Extracted claims</h3></div>{#each report.claims as claim}<article class="claim-item"><b>{claim.importance}</b><p>{claim.text}</p></article>{/each}</section><section><div class="section-label"><span>03</span><h3>Evidence assessment</h3></div><div class="evidence-columns"><div><h4>Supporting evidence</h4>{#if report.result.evidenceFor.length}{#each report.result.evidenceFor as item}<article class="evidence-item for"><i>+</i><p>{item.text}{#if item.sourceUrl}<a href={item.sourceUrl} target="_blank" rel="noreferrer">Open source ↗</a>{/if}</p></article>{/each}{:else}<p class="empty-evidence">No supporting evidence was confirmed.</p>{/if}</div><div><h4>Contradicting evidence</h4>{#if report.result.evidenceAgainst.length}{#each report.result.evidenceAgainst as item}<article class="evidence-item against"><i>−</i><p>{item.text}{#if item.sourceUrl}<a href={item.sourceUrl} target="_blank" rel="noreferrer">Open source ↗</a>{/if}</p></article>{/each}{:else}<p class="empty-evidence">No contradicting evidence was confirmed.</p>{/if}</div></div></section><section><div class="section-label"><span>04</span><h3>Auditable reasoning trace</h3></div><div class="trace-list">{#each report.result.reasoningTrace as trace}<article><b>{trace.step.toString().padStart(2,'0')}</b><div><h4>{trace.label}</h4><p>{trace.finding}</p>{#if trace.evidenceRefs.length}<small>{trace.evidenceRefs.join(' · ')}</small>{/if}</div></article>{/each}</div></section></div>
      <aside class="report-side"><section><h3>Gonka inference proof</h3><p>Each identifier below came from a specific inference response.</p>{#each report.runs as run}<article class="request-proof"><span>{run.stage}</span><strong>{run.model}</strong><code>{run.requestId}</code></article>{/each}</section><section><h3>Retrieved sources</h3>{#if report.sources.length}{#each report.sources as source}<article class:unavailable={source.status!=='retrieved'} class="source-proof"><i></i><div><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a><span>{source.status}{source.note?` · ${source.note}`:''}</span></div></article>{/each}{:else}<p class="empty-evidence">No external source was supplied. Current claims may remain unverifiable.</p>{/if}</section><section><h3>Uncertainty and limits</h3><ul>{#each report.result.uncertainties as item}<li>{item}</li>{/each}</ul><p class="consensus-note">{report.consensus.note}</p></section>{#if report.result.citations.length}<section><h3>Citations</h3>{#each report.result.citations as citation}<a class="citation" href={citation.url} target="_blank" rel="noreferrer">{citation.title}<span>↗</span></a>{/each}</section>{/if}</aside>
    </div></section>{/if}
</main></div>
