import { json } from '@sveltejs/kit';import { rpc,formatUnits } from '$server/providers/RpcProvider';import { resolveHandle } from '$server/providers/HandleResolver';
const txPattern=/^0x[a-fA-F0-9]{64}$/;const addressPattern=/^0x[a-fA-F0-9]{40}$/;
const explorers:Record<number,string>={11155111:'https://eth-sepolia.blockscout.com',84532:'https://base-sepolia.blockscout.com'};
async function addressActivity(chainId:number,address:string,page:number){const base=explorers[chainId];if(!base)return{items:[],source:'unavailable'};try{const response=await fetch(`${base}/api/v2/addresses/${address}/transactions?filter=to%20%7C%20from`);if(!response.ok)throw new Error();const body=await response.json();return{items:(body.items||[]).slice((page-1)*10,page*10),source:base};}catch{return{items:[],source:'unavailable'};}}
export const GET=async({url})=>{const chainId=Number(url.searchParams.get('chainId'));const query=url.searchParams.get('query')?.trim()||'latest';const page=Math.max(1,Number(url.searchParams.get('page'))||1);try{
  if(addressPattern.test(query)||query.toLowerCase().endsWith('.eth')){const address=await resolveHandle(query);const [balance,code,nonce,activity]=await Promise.all([rpc(chainId,'eth_getBalance',[address,'latest']),rpc(chainId,'eth_getCode',[address,'latest']),rpc(chainId,'eth_getTransactionCount',[address,'latest']),addressActivity(chainId,address,page)]);const contract=code!=='0x'&&code!=='0x0';return json({type:contract?'contract':'address',result:{identity:query,address,balance:formatUnits(balance),nonce:Number(nonce),contract,verifiedSource:contract&&activity.source!=='unavailable'?'check explorer':'not applicable',sourceCodeUrl:contract&&activity.source!=='unavailable'?`${activity.source}/address/${address}?tab=contract`:null,transactions:activity.items,activitySource:activity.source,page}});}
  if(txPattern.test(query)){const [transaction,receipt]=await Promise.all([rpc(chainId,'eth_getTransactionByHash',[query]),rpc(chainId,'eth_getTransactionReceipt',[query])]);if(!transaction)return json({error:'No transaction found.'},{status:404});const block=transaction.blockHash?await rpc(chainId,'eth_getBlockByHash',[transaction.blockHash,false]):null;return json({type:'transaction',result:{...transaction,status:receipt?.status==='0x1'?'success':receipt?.status==='0x0'?'failed':'pending',gasUsed:receipt?.gasUsed,logs:receipt?.logs||[],timestamp:block?.timestamp?new Date(Number(block.timestamp)*1000).toISOString():null}});}
  const tag=/^\d+$/.test(query)?'0x'+Number(query).toString(16):query;const block=await rpc(chainId,'eth_getBlockByNumber',[tag,false]);if(!block)return json({error:'No block found.'},{status:404});return json({type:'block',result:{...block,transactions:(block.transactions||[]).slice((page-1)*20,page*20),transactionCount:(block.transactions||[]).length,page}});
}catch(error){return json({error:error instanceof Error?error.message:'Explorer request failed'},{status:502});}};
