<script lang="ts">
  import AppHeader from '$components/AppHeader.svelte'; import { chains } from '$lib/config/chains';
  let address=''; let loading=false; let error=''; let fetchedAt=''; let copied=false;
  let balances: Array<{chainId:number;name:string;symbol:string;amount:string;status:string;error?:string}> = [];
  async function loadPortfolio(){ if(!/^0x[a-fA-F0-9]{40}$/.test(address.trim())){error='Enter a complete 0x EVM wallet address.';return;} loading=true;error='';try{const r=await fetch(`/api/portfolio?address=${encodeURIComponent(address.trim())}`);const data=await r.json();if(!r.ok)throw new Error(data.error);balances=data.balances;fetchedAt=data.fetchedAt;}catch(e){error=e instanceof Error?e.message:'Portfolio request failed';}finally{loading=false;} }
  async function connect(){try{const eth=(window as unknown as {ethereum?:{request:(a:{method:string})=>Promise<string[]>}}).ethereum;if(!eth)throw new Error('Install MetaMask or another EVM wallet first.');const accounts=await eth.request({method:'eth_requestAccounts'});address=accounts[0]||'';if(address)await loadPortfolio();}catch(e){error=e instanceof Error?e.message:'Wallet connection failed';}}
  async function copy(){if(!address)return;await navigator.clipboard.writeText(address);copied=true;setTimeout(()=>copied=false,1200);}
</script>
<svelte:head><title>Portfolio — Poké</title><meta name="description" content="Inspect native balances across supported EVM testnets."/></svelte:head>
<AppHeader active="portfolio" />
<main class="route-page">
  <section class="route-title"><div><span class="eyebrow">CROSS-CHAIN PORTFOLIO</span><h1>Your wallet,<br/><em>one clear view.</em></h1><p>Query native balances across Ethereum Sepolia, Base Sepolia, and Polygon Amoy from one address.</p></div><div class="route-actions"><button class="secondary" onclick={connect}>Connect wallet</button></div></section>
  <section class="lookup-card"><form onsubmit={(e)=>{e.preventDefault();loadPortfolio()}}><label for="wallet">Wallet address</label><div class="route-search"><span>0x</span><input id="wallet" bind:value={address} placeholder="0x1234…"/><button disabled={loading}>{loading?'Loading…':'Load portfolio'}</button></div>{#if error}<p class="form-error">{error}</p>{:else}<p class="form-help">Public RPC data · no wallet signature required</p>{/if}</form></section>
  <section class="portfolio-grid">
    <div class="summary-card"><span class="eyebrow">WALLET IDENTITY</span><div class="wallet-id"><div class="avatar large">0x</div><div><strong>{address ? `${address.slice(0,10)}…${address.slice(-8)}`:'No wallet loaded'}</strong><small>{fetchedAt?`Updated ${new Date(fetchedAt).toLocaleString()}`:'Search an address or connect your wallet'}</small></div><button onclick={copy} disabled={!address}>{copied?'Copied':'Copy'}</button></div><div class="portfolio-stats"><div><small>Networks reached</small><strong>{balances.filter(x=>x.status==='ok').length} / {chains.length}</strong></div><div><small>Assets tracked</small><strong>{balances.length || '—'}</strong></div><div><small>Data source</small><strong>Public RPC</strong></div></div></div>
    <div class="asset-card"><div class="section-head"><div><span class="eyebrow">NATIVE ASSETS</span><h2>Balances by network</h2></div><button onclick={loadPortfolio} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div>{#if error}<p class="portfolio-refresh-error" role="alert">{error}</p>{/if}<div class="asset-table"><div class="table-head"><span>Network</span><span>Asset</span><span>Balance</span><span>Status</span></div>{#each chains as chain}{@const balance=balances.find(x=>x.chainId===chain.id)}<div class="table-row"><div><i style={`background:${chain.color}`}></i><span><strong>{chain.name}</strong><small>Chain ID {chain.id}</small></span></div><b>{chain.symbol}</b><code>{balance?.amount??'—'}</code><span class:ok={balance?.status==='ok'} class="status">{balance?.status??'Waiting'}</span></div>{/each}</div></div>
  </section>
  <section class="coming-grid"><article><span>◎</span><div><strong>ERC-20 token discovery</strong><p>Query token metadata and wallet balances from known contracts.</p></div><a href="/portfolio/tokens">Next</a></article><article><span>◇</span><div><strong>NFT gallery</strong><p>Verify ERC-721 ownership and inspect token URI records.</p></div><a href="/portfolio/nfts">Next</a></article><article><span>↗</span><div><strong>Transaction activity</strong><p>Open Explorer to inspect a transaction or block live.</p></div><a href="/explorer">Explore</a></article></section>
</main>
