<script lang="ts">
  import AppHeader from '$components/AppHeader.svelte';import {chains} from '$lib/config/chains';import {onMount} from 'svelte';
  type Balance={chainId:number;name:string;symbol:string;amount:string;unitPrice:number|null;usdValue:number|null;status:string;error?:string};
  type Token={chainId:number;contract:string;name:string;symbol:string;logo:string|null;balance:number;unitPrice:number|null;usdValue:number|null};type Nft={chainId:number;contract:string;collection:string;symbol:string;tokenId:string;image:string|null;floorPrice:number|null};
  type Snapshot={identity:string;address:string;balances:Balance[];tokens:Token[];nfts:Nft[];dataSources:Array<{chainId:number;status:string;error?:string}>;totalUsd:number;fetchedAt:string;error?:string};
  let input='';let loading=false;let error='';let snapshots:Snapshot[]=[];let selected='all';let chainFilter='all';
  $: shown=selected==='all'?snapshots:snapshots.filter(item=>item.identity===selected);
  $: rows=shown.flatMap(item=>item.balances.map(balance=>({...balance,identity:item.identity,address:item.address}))).filter(item=>chainFilter==='all'||String(item.chainId)===chainFilter).sort((a,b)=>(b.usdValue||0)-(a.usdValue||0));
  $: tokenRows=shown.flatMap(item=>item.tokens.map(token=>({...token,identity:item.identity}))).filter(item=>chainFilter==='all'||String(item.chainId)===chainFilter).sort((a,b)=>(b.usdValue||0)-(a.usdValue||0));
  $: nftRows=shown.flatMap(item=>item.nfts.map(nft=>({...nft,identity:item.identity}))).filter(item=>chainFilter==='all'||String(item.chainId)===chainFilter);
  $: combined=snapshots.reduce((sum,item)=>sum+item.totalUsd,0);
  onMount(()=>{const saved=JSON.parse(localStorage.getItem('poke-watchlist')||'[]') as string[];if(saved.length){input=saved[0];for(const identity of saved.slice(0,10))load(identity,false);}});
  async function load(identity=input,save=true){if(!identity.trim())return;loading=true;error='';try{const response=await fetch(`/api/portfolio?address=${encodeURIComponent(identity.trim())}`);const data=await response.json();if(!response.ok)throw new Error(data.error);const snapshot:Snapshot=data;snapshots=[...snapshots.filter(item=>item.identity.toLowerCase()!==snapshot.identity.toLowerCase()),snapshot];if(save){const watch=[...new Set([...snapshots.map(item=>item.identity),snapshot.identity])].slice(0,10);localStorage.setItem('poke-watchlist',JSON.stringify(watch));}selected=snapshot.identity;}catch(e){error=e instanceof Error?e.message:'Portfolio request failed.';}finally{loading=false;}}
  function remove(identity:string){snapshots=snapshots.filter(item=>item.identity!==identity);localStorage.setItem('poke-watchlist',JSON.stringify(snapshots.map(item=>item.identity)));if(selected===identity)selected='all';}
  async function connect(){try{const eth=(window as unknown as {ethereum?:{request:(a:{method:string})=>Promise<string[]>}}).ethereum;if(!eth)throw new Error('Install MetaMask first.');input=(await eth.request({method:'eth_requestAccounts'}))[0]||'';if(input)await load();}catch(e){error=e instanceof Error?e.message:'Wallet connection failed.';}}
</script>
<svelte:head><title>Portfolio — Poké</title></svelte:head><AppHeader active="portfolio"/>
<main class="route-page"><section class="route-title"><div><span class="eyebrow">MULTI-ADDRESS PORTFOLIO</span><h1>Your wallets,<br/><em>one clear view.</em></h1><p>Watch addresses or ENS names across Ethereum Sepolia, Base Sepolia, and Polygon Amoy.</p></div><button class="secondary" onclick={connect}>Connect wallet</button></section>
<section class="lookup-card"><form onsubmit={(e)=>{e.preventDefault();load()}}><label for="wallet">Wallet address or ENS name</label><div class="route-search"><span>0x</span><input id="wallet" bind:value={input} placeholder="0x… or name.eth"/><button disabled={loading}>{loading?'Loading…':'Add to watchlist'}</button></div>{#if error}<p class="form-error">{error}</p>{:else}<p class="form-help">ENS resolves through the handle-provider adapter. Each network degrades independently.</p>{/if}</form></section>
<section class="summary-card"><span class="eyebrow">ALL WATCHED ADDRESSES</span><h1>${combined.toLocaleString(undefined,{maximumFractionDigits:2})}</h1><div class="chainbar"><button class:active={selected==='all'} onclick={()=>selected='all'}>Combined</button>{#each snapshots as item}<span><button class:active={selected===item.identity} onclick={()=>selected=item.identity}>{item.identity}</button><button aria-label={`Remove ${item.identity}`} onclick={()=>remove(item.identity)}>×</button></span>{/each}</div><div class="chainbar"><button class:active={chainFilter==='all'} onclick={()=>chainFilter='all'}>All chains</button>{#each chains as chain}<button class:active={chainFilter===String(chain.id)} onclick={()=>chainFilter=String(chain.id)}><span style={`background:${chain.color}`}></span>{chain.name}</button>{/each}</div></section>
<section class="asset-card"><div class="section-head"><div><span class="eyebrow">SORTED BY USD VALUE</span><h2>Native assets</h2></div><a href="/portfolio/tokens">ERC-20 discovery →</a></div><div class="asset-table"><div class="table-head"><span>Network / identity</span><span>Asset</span><span>Balance / USD</span><span>Status</span></div>{#each rows as row}<div class="table-row"><div><i style={`background:${chains.find(c=>c.id===row.chainId)?.color}`}></i><span><strong>{row.name}</strong><small>{row.identity}</small></span></div><b>{row.symbol}</b><code>{row.amount}<small>{row.usdValue==null?'Price unavailable':`$${row.usdValue.toFixed(2)} · $${row.unitPrice?.toLocaleString()} ea.`}</small></code><span class:ok={row.status==='ok'} class="status">{row.status}</span></div>{/each}{#if !rows.length}<p class="form-help">Add an address or ENS name to load balances.</p>{/if}</div></section>
<section class="asset-card"><div class="section-head"><div><span class="eyebrow">INDEXER ADAPTER</span><h2>ERC-20 holdings</h2></div></div><div class="asset-table">{#each tokenRows as token}<div class="table-row"><div>{#if token.logo}<img src={token.logo} alt="" width="24" height="24" loading="lazy"/>{:else}<i></i>{/if}<span><strong>{token.name}</strong><small>{token.identity}</small></span></div><b>{token.symbol}</b><code>{token.balance}<small>{token.usdValue==null?'Price unavailable':`$${token.usdValue.toFixed(2)}`}</small></code><span class="status ok">indexed</span></div>{/each}{#if !tokenRows.length}<p class="form-help">No indexed ERC-20 balances were returned. Use manual discovery if the testnet indexer is incomplete.</p>{/if}</div></section>
<section class="asset-card"><div class="section-head"><div><span class="eyebrow">LAZY-LOADED NFT GRID</span><h2>NFTs grouped by collection</h2></div></div><div class="nft-grid">{#each nftRows as nft}<article><div class="nft-art">{#if nft.image}<img src={nft.image} alt={nft.collection} loading="lazy"/>{:else}<span>{nft.symbol}</span>{/if}<strong>#{nft.tokenId}</strong></div><div class="nft-info"><h3>{nft.collection}</h3><small>{nft.identity} · Floor unavailable</small></div></article>{/each}{#if !nftRows.length}<p class="form-help">No indexed NFT holdings were returned for the selected view.</p>{/if}</div></section>
<section class="coming-grid"><article><span>◎</span><div><strong>ERC-20 token discovery</strong><p>Read known token contracts through the shared RPC provider.</p></div><a href="/portfolio/tokens">Open</a></article><article><span>◇</span><div><strong>NFT gallery</strong><p>Lazy-load verified ownership and token URI data.</p></div><a href="/portfolio/nfts">Open</a></article><article><span>↗</span><div><strong>Explorer</strong><p>Inspect blocks, transactions, addresses, and contracts.</p></div><a href="/explorer">Open</a></article></section></main>
