<script lang="ts">
  import {onMount} from 'svelte';type Message={role:'user'|'assistant';content:string;model?:string;requestId?:string};
  let open=false;let input='';let loading=false;let messages:Message[]=[{role:'assistant',content:'Ask about the current Poké page, wallet, chain, verification evidence, or Web3 safety.'}];
  onMount(()=>{const saved=localStorage.getItem('poke-chat');if(saved)try{messages=JSON.parse(saved);}catch{}});
  async function send(){if(!input.trim()||loading)return;const text=input.trim();messages=[...messages,{role:'user',content:text}];input='';loading=true;try{
    const scans=JSON.parse(localStorage.getItem('poke-scam-scans')||'[]');const reports=JSON.parse(localStorage.getItem('poke-reports')||'[]');const context=`Current screen source: ${location.pathname}. Latest cached scam verification: ${JSON.stringify(scans[0]||null).slice(0,3500)}. Saved report metadata: ${JSON.stringify(reports.slice(0,3)).slice(0,2000)}. Cite facts as Current screen context or Saved local record. A hash alone proves only integrity.`;
    const response=await fetch('/api/ai/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stream:true,messages:[{role:'user',content:context},...messages.slice(-10).map(({role,content})=>({role,content}))]})});if(!response.ok){const body=await response.json();throw new Error(body.error);}
    const assistant:Message={role:'assistant',content:''};messages=[...messages,assistant];const reader=response.body?.getReader();const decoder=new TextDecoder();let pending='';while(reader){const {done,value}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});const lines=pending.split('\n');pending=lines.pop()||'';for(const line of lines){if(!line)continue;const event=JSON.parse(line);if(event.delta){assistant.content+=event.delta;messages=[...messages.slice(0,-1),{...assistant}];}if(event.done){assistant.model=event.model;assistant.requestId=event.requestId;messages=[...messages.slice(0,-1),{...assistant}];}}}localStorage.setItem('poke-chat',JSON.stringify(messages.slice(-20)));
  }catch{messages=[...messages,{role:'assistant',content:'The assistant is temporarily unavailable.'}];}finally{loading=false;}}
</script>
<button class="chat-fab" onclick={()=>open=!open}><span>✦</span><div><strong>Chatbot corner</strong><small>Persistent · GonkaRouter</small></div><b>↑</b></button>
{#if open}<section class="chat"><header><div><span>✦</span><div><strong>Poké assistant</strong><small>Context: {typeof location==='undefined'?'/':location.pathname}</small></div></div><button onclick={()=>open=false}>×</button></header><div class="messages" aria-live="polite">{#each messages as message}<p class={message.role}>{message.content}{#if message.model}<small class="chat-proof">Source: Current screen context · {message.model} · {message.requestId}</small>{/if}</p>{/each}{#if loading}<p>Streaming a sourced answer…</p>{/if}</div><form onsubmit={(e)=>{e.preventDefault();send()}}><input bind:value={input} aria-label="Chat message" placeholder="Ask about this view…"/><button disabled={loading}>↑</button></form></section>{/if}
