<script lang="ts">
  import { onMount } from 'svelte';
  type EthereumProvider={request:(args:{method:string;params?:unknown[]})=>Promise<unknown>;on?:(event:string,handler:(value?:unknown)=>void)=>void;removeListener?:(event:string,handler:(value?:unknown)=>void)=>void};
  type User={wallet:string;expiresAt:number}; let user:User|null=null; let open=false; let step:'connect'|'signing'|'error'='connect'; let error=''; let busy=false;
  const provider=()=>((window as unknown as {ethereum?:EthereumProvider}).ethereum);
  onMount(()=>{refresh();const ethereum=provider();const reset=async()=>{if(user){await fetch('/api/auth/session',{method:'DELETE'}).catch(()=>{});user=null;}};ethereum?.on?.('accountsChanged',reset);ethereum?.on?.('disconnect',reset);return()=>{ethereum?.removeListener?.('accountsChanged',reset);ethereum?.removeListener?.('disconnect',reset);};});
  async function refresh(){try{const data=await fetch('/api/auth/session').then(r=>r.json());user=data.user;}catch{user=null;}}
  async function login(){busy=true;error='';try{const ethereum=provider();if(!ethereum)throw new Error('MetaMask was not detected. Install it or open Poké in the browser where your wallet extension is enabled.');const accounts=await ethereum.request({method:'eth_requestAccounts'}) as string[];const address=accounts[0];if(!address)throw new Error('No wallet account was selected.');step='signing';const challengeResponse=await fetch('/api/auth/nonce',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address})});const challenge=await challengeResponse.json();if(!challengeResponse.ok)throw new Error(challenge.error);const signature=await ethereum.request({method:'personal_sign',params:[challenge.message,address]}) as string;const verifyResponse=await fetch('/api/auth/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address,message:challenge.message,signature})});const verified=await verifyResponse.json();if(!verifyResponse.ok)throw new Error(verified.error);user=verified.user;open=false;step='connect';}catch(e){const code=(e as {code?:number})?.code;error=code===4001?'The wallet request was cancelled. You can try again when ready.':e instanceof Error?e.message:'Wallet sign-in failed.';step='error';}finally{busy=false;}}
  function short(value:string){return `${value.slice(0,6)}…${value.slice(-4)}`;}
</script>
{#if user}<a class="account-link" href="/profile"><span class="account-dot"></span>{short(user.wallet)}</a>{:else}<button class="auth-trigger" onclick={()=>open=true}>Sign in</button>{/if}
{#if open}<div class="auth-overlay" role="presentation" onclick={(e)=>{if(e.target===e.currentTarget&&!busy)open=false}}><div class="auth-dialog" role="dialog" aria-modal="true" aria-labelledby="auth-title"><button class="auth-close" onclick={()=>open=false} disabled={busy}>×</button><div class="auth-brand"><span class="mark">P</span><span>poké secure access</span></div><h2 id="auth-title">Sign in with your wallet</h2><p>No password is stored. You will sign a one-time message that cannot move funds or cost gas.</p><div class="auth-safety"><span>✓ No transaction</span><span>✓ No seed phrase</span><span>✓ 5-minute challenge</span></div>{#if step==='signing'}<div class="auth-progress"><i></i><div><strong>Check your wallet</strong><small>Approve the one-time login signature.</small></div></div>{:else}<button class="auth-primary" onclick={login} disabled={busy}>{busy?'Connecting…':'Connect MetaMask'}</button>{/if}{#if error}<div class="auth-error" role="alert">{error}</div><button class="auth-secondary" onclick={()=>{step='connect';error=''}}>Try again</button>{/if}<small class="auth-footnote">Poké will never ask for your recovery phrase or private key.</small></div></div>{/if}
