<script lang="ts">
  import { onMount } from 'svelte';
  import { env } from '$env/dynamic/public';
  import { encodeFunctionData, parseAbi } from 'viem';

  export let open=false;
  type User={wallet:string;expiresAt:number};
  type Evidence={id:string;name:string;size:number;type:string;hash:string;data:string};
  let user:User|null=null;let report='';let reportHash='';let evidenceFiles:Evidence[]=[];let busy=false;let error='';let saved=false;let txHash='';let disclosure='';let expectedHash='';let verifyResult='';let recoveryKey='';
  const abi=parseAbi(['function attest(bytes32 reportHash, bytes32 schema)','function verify(bytes32 reportHash) view returns (bool)']);
  const zeroHash=`0x${'0'.repeat(64)}` as `0x${string}`;
  const hex=(buffer:ArrayBuffer)=>'0x'+[...new Uint8Array(buffer)].map(x=>x.toString(16).padStart(2,'0')).join('');
  const b64=(bytes:Uint8Array)=>{let value='';for(let i=0;i<bytes.length;i+=32768)value+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(value);};
  const refresh=async()=>{const data=await fetch('/api/auth/session').then(r=>r.json()).catch(()=>({user:null}));user=data.user;};
  onMount(refresh);
  const commitment=()=>JSON.stringify({version:1,report:report.trim(),evidence:evidenceFiles.map(({name,size,type,hash})=>({name,size,type,sha256:hash}))});
  async function addEvidence(event:Event){const input=event.currentTarget as HTMLInputElement;error='';for(const file of Array.from(input.files||[]).slice(0,5-evidenceFiles.length)){if(file.size>10*1024*1024){error='Each file must be 10 MB or smaller.';continue;}const buffer=await file.arrayBuffer();evidenceFiles=[...evidenceFiles,{id:crypto.randomUUID(),name:file.name,size:file.size,type:file.type||'application/octet-stream',hash:hex(await crypto.subtle.digest('SHA-256',buffer)),data:b64(new Uint8Array(buffer))}];}input.value='';reportHash='';saved=false;}
  async function generate(){await refresh();if(!user){error='Sign in with your wallet before creating a whistleblower proof.';return;}reportHash=hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(commitment())));saved=false;error='';}
  async function encryptedRecord(){const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const plaintext=new TextEncoder().encode(JSON.stringify({report:report.trim(),evidence:evidenceFiles}));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plaintext);return{ciphertext:b64(new Uint8Array(ciphertext)),iv:b64(iv),key:b64(new Uint8Array(await crypto.subtle.exportKey('raw',key)))};}
  async function save(){await refresh();if(!user||!reportHash)return;busy=true;error='';try{const quotaResponse=await fetch('/api/reports/quota',{method:'POST'});const quota=await quotaResponse.json();if(!quotaResponse.ok)throw new Error(quota.error);const encrypted=await encryptedRecord();recoveryKey=encrypted.key;sessionStorage.setItem(`poke-report-key:${reportHash}`,recoveryKey);const records=JSON.parse(localStorage.getItem('poke-reports')||'[]') as Array<Record<string,unknown>>;const record={hash:reportHash,owner:user.wallet,encrypted:{ciphertext:encrypted.ciphertext,iv:encrypted.iv},createdAt:new Date().toISOString(),quota};localStorage.setItem('poke-reports',JSON.stringify([record,...records.filter(item=>item.hash!==reportHash)].slice(0,30)));saved=true;}catch(e){error=e instanceof Error?e.message:'Could not encrypt and save the report.';}finally{busy=false;}}
  async function anchor(){await refresh();if(!user||!reportHash){error='Sign in and generate the proof first.';return;}const contract=env.PUBLIC_ATTESTATION_CONTRACT;if(!/^0x[a-fA-F0-9]{40}$/.test(contract||'')){error='Set PUBLIC_ATTESTATION_CONTRACT after deploying the registry contract.';return;}const ethereum=(window as unknown as {ethereum?:{request:(args:{method:string;params?:unknown[]})=>Promise<unknown>}}).ethereum;if(!ethereum){error='MetaMask is required to anchor the proof.';return;}busy=true;error='';try{const accounts=await ethereum.request({method:'eth_requestAccounts'}) as string[];if(accounts[0]?.toLowerCase()!==user.wallet.toLowerCase())throw new Error('Use the same wallet that signed in to Poké.');const data=encodeFunctionData({abi,functionName:'attest',args:[reportHash as `0x${string}`,zeroHash]});txHash=String(await ethereum.request({method:'eth_sendTransaction',params:[{from:accounts[0],to:contract,data}]}));}catch(e){error=e instanceof Error?e.message:'Attestation transaction failed.';}finally{busy=false;}}
  async function verifyDisclosure(){verifyResult='';error='';try{const parsed=JSON.parse(disclosure);const canonical=JSON.stringify(parsed);const actual=hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical)));if(actual.toLowerCase()!==expectedHash.trim().toLowerCase()){verifyResult=`Mismatch — recomputed ${actual}`;return;}let chain='Hash matches the disclosed package.';if(/^0x[a-fA-F0-9]{40}$/.test(env.PUBLIC_ATTESTATION_CONTRACT||'')){const ethereum=(window as unknown as {ethereum?:{request:(args:{method:string;params?:unknown[]})=>Promise<unknown>}}).ethereum;if(ethereum){const data=encodeFunctionData({abi,functionName:'verify',args:[actual as `0x${string}`]});const result=String(await ethereum.request({method:'eth_call',params:[{to:env.PUBLIC_ATTESTATION_CONTRACT,data},'latest']}));chain+=result.endsWith('1')?' On-chain attestation found.':' No on-chain attestation found on the connected network.';}}verifyResult=chain;}catch{error='Paste a valid disclosure JSON package and its expected 0x hash.';}}
</script>

{#if open}<div class="modal" role="presentation" onclick={(e)=>{if(e.target===e.currentTarget)open=false}}><div class="report-dialog" role="dialog" aria-modal="true" aria-labelledby="report-title"><button class="close" onclick={()=>open=false}>×</button><span class="eyebrow">WALLET-GATED WHISTLEBLOWING</span><h2 id="report-title">Create tamper-evident proof</h2><p>The report and evidence are hashed locally, encrypted before off-chain browser storage, and can be anchored through your wallet when a registry contract is configured.</p>{#if !user}<p class="limit-warning">Sign in with the header wallet button before submitting a report.</p>{/if}<label for="report">Report content</label><textarea id="report" bind:value={report} oninput={()=>{reportHash='';saved=false}} placeholder="Describe what happened without identifying yourself…"></textarea><div class="evidence-upload"><div><strong>Evidence attachments</strong><small>Up to 5 files · 10 MB each · hashed before storage</small></div><label class="upload-button" for="evidence">+ Add files</label><input id="evidence" type="file" multiple onchange={addEvidence}/></div>{#each evidenceFiles as file}<div class="hash"><strong>{file.name}</strong><code>{file.hash}</code></div>{/each}<button class="full primary" onclick={generate} disabled={!report.trim()||busy}>Generate report + evidence hash</button>{#if reportHash}<div class="hash"><small>Combined SHA-256 commitment</small><code>{reportHash}</code></div><button class="full primary" onclick={save} disabled={saved||busy}>{saved?'Encrypted proof saved':'Encrypt and save off-chain'}</button><button class="full primary" onclick={anchor} disabled={busy}>{txHash?'Attestation submitted':'Anchor hash on testnet'}</button><button class="full" onclick={()=>navigator.clipboard.writeText(commitment())}>Copy disclosure package</button>{/if}{#if txHash}<div class="hash"><small>Attestation transaction</small><code>{txHash}</code></div>{/if}<details><summary>Verify a disclosed report</summary><label for="expected-hash">Expected report hash</label><input id="expected-hash" bind:value={expectedHash} placeholder="0x…"/><label for="disclosure">Disclosure JSON package</label><textarea id="disclosure" bind:value={disclosure} placeholder="Paste the disclosure JSON package"></textarea><button class="full primary" onclick={verifyDisclosure}>Recompute and verify</button>{#if verifyResult}<p>{verifyResult}</p>{/if}</details>{#if error}<p class="limit-warning">{error}</p>{/if}</div></div>{/if}
