<script lang="ts">
  import AppHeader from '$components/AppHeader.svelte';import {chains} from '$lib/config/chains';
  let activeChain:(typeof chains)[number]=chains[0];let query='latest';let loading=false;let error='';let kind='';let result:Record<string,any>|null=null;let page=1;
  async function explore(value=query,nextPage=1){query=value;page=nextPage;loading=true;error='';result=null;try{const response=await fetch(`/api/explorer?chainId=${activeChain.id}&page=${page}&query=${encodeURIComponent(query.trim()||'latest')}`);const data=await response.json();if(!response.ok)throw new Error(data.error);kind=data.type;result=data.result;}catch(e){error=e instanceof Error?e.message:'Explorer request failed.';}finally{loading=false;}}
  function choose(chain:(typeof chains)[number]){activeChain=chain;result=null;error='';query='latest';page=1;}
  const entries=()=>result?Object.entries(result).filter(([key,value])=>!['transactions','logs'].includes(key)&&value!=null&&typeof value!=='object'):[];
</script>
<svelte:head><title>Cross-EVM Explorer — Poké</title></svelte:head><AppHeader active="explorer"/>
<main class="route-page explorer-page"><section class="explorer-hero"><div><span class="eyebrow">CROSS-EVM EXPLORER</span><h1>Network Explorer</h1><p>Inspect an address, ENS name, transaction, or block across all three MVP testnets.</p></div><div class="network-pill"><i style={`background:${activeChain.color}`}></i><span><small>ACTIVE NETWORK</small><strong>{activeChain.name}</strong></span><code>{activeChain.id}</code></div></section>
<section class="network-section"><div class="network-cards">{#each chains as chain}<button class:active={activeChain.id===chain.id} onclick={()=>choose(chain)} style={`--network:${chain.color}`}><span class="network-icon">{chain.symbol[0]}</span><div><strong>{chain.name}</strong><small>Chain ID {chain.id}</small></div><b>{activeChain.id===chain.id?'Selected':'Open'} →</b></button>{/each}</div></section>
<section class="explorer-workbench"><div class="workbench-head"><div><span class="eyebrow">UNIVERSAL LOOKUP</span><h2>Inspect {activeChain.name}</h2></div><button class="latest" onclick={()=>explore('latest')}>Latest block</button></div><form onsubmit={(e)=>{e.preventDefault();explore()}}><label for="explorer-query">Address, ENS name, transaction hash, or block</label><div class="route-search"><span>⌕</span><input id="explorer-query" bind:value={query} placeholder="name.eth, 0x address/hash, latest, or block number"/><button disabled={loading}>{loading?'Querying…':'Explore'}</button></div>{#if error}<p class="form-error">{error}</p>{:else}<p class="form-help">RPC and explorer-indexer adapters fail independently.</p>{/if}</form>
{#if result}<div class="explorer-result"><div class="result-title"><span class="result-type">{kind}</span><h3>{kind==='transaction'?'Transaction details':kind==='block'?'Block details':'Address / contract details'}</h3>{#if kind==='address'||kind==='contract'}<a href={`/?panel=scam&target=${encodeURIComponent(result.address)}`}>Open cached verification</a>{/if}<button onclick={()=>navigator.clipboard.writeText(JSON.stringify(result))}>Copy JSON</button></div><div class="field-grid">{#each entries() as [key,value]}<div><small>{key.replaceAll(/([A-Z])/g,' $1')}</small>{#if key==='sourceCodeUrl'}<a href={String(value)} target="_blank" rel="noreferrer">View verified-source status ↗</a>{:else}<code>{String(value)}</code>{/if}</div>{/each}</div>
{#if result.transactions}<div class="scan-evidence"><h4>Transactions ({result.transactionCount??result.transactions.length})</h4><ul>{#each result.transactions as tx}<li><code>{typeof tx==='string'?tx:tx.hash}</code></li>{/each}</ul><button disabled={page===1} onclick={()=>explore(query,page-1)}>Previous</button><button disabled={result.transactions.length===0} onclick={()=>explore(query,page+1)}>Next</button></div>{/if}{#if result.logs}<details><summary>Raw or decoded logs when ABI is available ({result.logs.length})</summary><pre>{JSON.stringify(result.logs,null,2)}</pre></details>{/if}<details><summary>Raw provider response</summary><pre>{JSON.stringify(result,null,2)}</pre></details></div>{:else}<div class="explorer-empty"><div>⌘</div><h3>Ready to explore</h3><p>Search an identity, transaction, or block.</p></div>{/if}</section></main>
