<script lang="ts">
  import AppHeader from '$components/AppHeader.svelte'; import { chains } from '$lib/config/chains';
  let activeChain:(typeof chains)[number]=chains[0]; let query='latest'; let loading=false; let error=''; let kind=''; let result:Record<string,unknown>|null=null;
  async function explore(value=query){query=value;loading=true;error='';result=null;try{const r=await fetch(`/api/explorer?chainId=${activeChain.id}&query=${encodeURIComponent(query.trim()||'latest')}`);const data=await r.json();if(!r.ok)throw new Error(data.error);kind=data.type;result=data.result;}catch(e){error=e instanceof Error?e.message:'Explorer request failed';}finally{loading=false;}}
  function choose(chain:(typeof chains)[number]){activeChain=chain;result=null;error='';query='latest';}
  const fields=()=>result?[['Hash',result.hash],['Block number',result.number?Number(result.number as string).toString():null],['Timestamp',result.timestamp?new Date(Number(result.timestamp as string)*1000).toLocaleString():null],['From',result.from],['To',result.to],['Gas',result.gas],['Transactions',Array.isArray(result.transactions)?result.transactions.length:null]].filter(x=>x[1]!=null):[];
</script>
<svelte:head><title>Network Explorer — Poké</title><meta name="description" content="Explore testnet blocks and transactions across supported EVM networks."/></svelte:head>
<AppHeader active="explorer" />
<main class="route-page explorer-page">
  <section class="explorer-hero"><div><span class="eyebrow">MULTI-CHAIN EXPLORER</span><h1>Network Explorer</h1><p>Select a network, then inspect its latest block, a block height, or a transaction hash.</p></div><div class="network-pill"><i style={`background:${activeChain.color}`}></i><span><small>ACTIVE NETWORK</small><strong>{activeChain.name}</strong></span><code>{activeChain.id}</code></div></section>
  <section class="network-section"><div class="section-head"><div><span class="eyebrow">PHASE 0 NETWORKS</span><h2>Choose a chain</h2></div><span class="online"><i></i> Public RPC</span></div><div class="network-cards">{#each chains as chain}<button class:active={activeChain.id===chain.id} onclick={()=>choose(chain)} style={`--network:${chain.color}`}><span class="network-icon">{chain.symbol[0]}</span><div><strong>{chain.name}</strong><small>Chain ID {chain.id}</small></div><b>{activeChain.id===chain.id?'Selected':'Open'} →</b></button>{/each}</div></section>
  <section class="explorer-workbench"><div class="workbench-head"><div><span class="eyebrow">LOOKUP</span><h2>Inspect {activeChain.name}</h2></div><button class="latest" onclick={()=>explore('latest')}>View latest block</button></div><form onsubmit={(e)=>{e.preventDefault();explore()}}><label for="explorer-query">Transaction hash or block number</label><div class="route-search"><span>⌕</span><input id="explorer-query" bind:value={query} placeholder="latest, 123456, or 0x transaction hash"/><button disabled={loading}>{loading?'Querying…':'Explore'}</button></div>{#if error}<p class="form-error">{error}</p>{:else}<p class="form-help">Queries go directly through Poké’s server-side RPC adapter.</p>{/if}</form>
    {#if result}<div class="explorer-result"><div class="result-title"><span class="result-type">{kind}</span><h3>{kind==='transaction'?'Transaction details':'Block details'}</h3><button onclick={()=>navigator.clipboard.writeText(JSON.stringify(result))}>Copy JSON</button></div><div class="field-grid">{#each fields() as field}<div><small>{field[0]}</small><code>{String(field[1])}</code></div>{/each}</div><details><summary>Raw RPC response</summary><pre>{JSON.stringify(result,null,2)}</pre></details></div>{:else}<div class="explorer-empty"><div>⌘</div><h3>Ready to explore</h3><p>Choose “View latest block” for an immediate live result, or search for a block or transaction.</p></div>{/if}
  </section>
</main>
